name: hive_db
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8

  intl: ^0.20.2           
  # Provides date formatting utilities (used for displaying formatted dates like yMMMd)

  table_calendar: ^3.0.9  
  # Powerful and customizable calendar widget (used to display calendar and select dates)

  hive_ce: ^2.15.1
  # Lightweight NoSQL database used for local storage (CRUD operations for Person data)

  hive_ce_flutter: ^2.3.3
  # Integrates Hive with Flutter (enables box initialization & ValueListenableBuilder)

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_ce_generator: ^1.10.0
  # Generates TypeAdapters for Hive models (automatically creates serialization code)

  build_runner: ^2.4.6     
  # Runs code generation tasks (required to execute hive_generator and produce adapter files ex. person_model.g.dart)

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - res/icon/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: poppins
      fonts:
        - asset: res/fonts/Poppins-Regular.ttf
    - family: amaranth
      fonts:
        - asset: res/fonts/Amaranth-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
